# StreamManager Configuration File

# Video source configuration
video_source:
  type: "usb_camera"  # Options: "gazebo_ros2", "usb_camera", "mavlink"
  topic_name: "/camera/image_raw"  # For ROS2/Gazebo
  device_id: 0  # For USB camera
  mavlink_address: "udp://127.0.0.1:14550"  # For MAVLink
  timeout_seconds: 5.0

# Frame buffer configuration
buffer:
  max_size: 3  # Maximum number of frames to keep in buffer
  target_fps: 50.0  # Target FPS for buffer filling (can be less than input FPS)

# Frame scaling configuration
scaling:
  enabled: false  # Enable/disable frame scaling
  target_width: 640
  target_height: 480
  interpolation_method: 1  # OpenCV interpolation method (0=NEAREST, 1=LINEAR, 2=CUBIC, etc.)

# ROS2 publishing configuration
publishing:
  current_frame_topic: "/stream_manager/current_frame"
  delayed_frame_topic: "/stream_manager/delayed_frame"
  delay_ms: 50  # Delay for delayed frame publishing in milliseconds
  enable_current_publishing: true
  enable_delayed_publishing: true

# Debug settings
enable_debug_logging: true